environment:
  name: dev
  project: <cdf-project>
  validation-type: dev
  selected:
  - modules/Session1


variables:
  modules:
    Session1:
      rmdm_model_space: session1_rmdm
      rmdm_model_views_version: '1.0.0'
      rmdm_instance_space: session1_rmdm_instance
    Session2:
      rmdm_model_space: session2_rmdm
      rmdm_model_views_version: '1.0.0'
      rmdm_instance_space: session2_rmdm_instance
